# -*- coding: utf-8 -*-
"""labeling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jwKFk4tC9FScOsg-LIMrUocByq9iIbHA
"""

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

responses = pd.read_csv("/content/drive/MyDrive/Cybersickness 설문(응답) user12(13번째)까지.csv", encoding='cp949')

## fms 응답만 모으기
fms = responses.loc[:,'비디오1':'비디오20']
fms

## 띄어쓰기 기준으로 응답 split해서
## user마다 array로 저장
labels = []
for i in range(len(fms)):
  label = []
  for j in range(20):
    split = fms.iloc[i,j].split()
    label.append([int(s) for s in split])
  labels.append(label)

labels

## preprocessed된 데이터셋에 label 붙이기
## video 데이터의 'Time' column 기준 1~15, 16~30, 31~45에 label 부여

import os

# 총 user 수
users = 11

for i in range(users):
  # 저장 경로
  output_path = '/content/drive/MyDrive/SKCC/modeling/labeled_data/user{num}'.format(num=str(i).zfill(2))
  os.mkdir(output_path)

  # 호출 경로
  user_path = '/content/drive/MyDrive/SKCC/modeling/preprocessed_data/user{num}'.format(num=str(i).zfill(2))
  
  # labeling 안 된 row 있는지 확인하는 용도의 list
  count_null = []

  for j in range(20):
    try:
      video = pd.read_csv(user_path+'/{video_num}.csv'.format(video_num=str(j+1).zfill(2)), index_col=False)
      video.drop(video.columns[0], axis=1, inplace=True)
    except Exception:
      print("There is no user{n}'s data".format(n=str(i).zfill(2)))
      break
    # 각 video에 target column 생성
    video['fms'] = None

    # 15초마다 같은 fms 값을 labeling
    video.loc[video['Time'] <= 15, 'fms'] = labels[i][j][0]
    video.loc[(video['Time'] > 15) & (video['Time'] <= 30), 'fms'] = labels[i][j][1]
    video.loc[video['Time'] > 30, 'fms'] = labels[i][j][2]
    count_null.append(len(video[video['fms']==None]))

    # 최종 video 파일들을 user별로 'labeled_data' 폴더에 저장
    video.to_csv(output_path+'/{n}_{video_num}.csv'.format(n=str(i).zfill(2), video_num=str(j+1).zfill(2)), encoding='utf-8', index=False)
  print(count_null)

